version: '3'
services:
    node:
        image: node/carbon
        networks:
           - internal
        ports:
          - "3000:3000"
    chrome:
        image: selenium/standalone-chrome
        networks:
           - internal
        ports:
          - "4444:4444"

networks:
    internal:
